class FoodItem {
  final String id;
  final String canteenId;
  final String name;
  final double price;
  final String prepTime;
  final String rating;
  final String img;
  final String category;
  final bool isVeg;
  final String desc;

  FoodItem({
    required this.id,
    required this.canteenId,
    required this.name,
    required this.price,
    required this.prepTime,
    required this.rating,
    required this.img,
    required this.category,
    required this.isVeg,
    required this.desc,
  });

  factory FoodItem.fromJson(Map<String, dynamic> json) {
    return FoodItem(
      id: json['id'] ?? '',
      canteenId: json['canteenId'] ?? 'canteen-1',
      name: json['name'] ?? '',
      price: (json['price'] as num?)?.toDouble() ?? 0.0,
      prepTime: json['prepTime'] ?? '',
      rating: json['rating'] ?? '',
      img: json['img'] ?? '',
      category: json['category'] ?? '',
      isVeg: json['isVeg'] ?? true,
      desc: json['desc'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'canteenId': canteenId,
      'name': name,
      'price': price,
      'prepTime': prepTime,
      'rating': rating,
      'img': img,
      'category': category,
      'isVeg': isVeg,
      'desc': desc,
    };
  }
}

// The full static Canteen Catalogue matching the React web app constants
final List<FoodItem> canteenCatalogue = [
  FoodItem(
    id: "item-1",
    canteenId: "canteen-1",
    name: "Paneer Butter Masala Combo",
    price: 120.0,
    prepTime: "10 min",
    rating: "4.8",
    img: "🍛",
    category: "Veg Specials",
    isVeg: true,
    desc: "Soft paneer cubes cooked in rich butter gravy, served with 2 Butter Rotis.",
  ),
  FoodItem(
    id: "item-2",
    canteenId: "canteen-1",
    name: "Classic Tomato Rice",
    price: 70.0,
    prepTime: "6 min",
    rating: "4.6",
    img: "🍅",
    category: "Veg Specials",
    isVeg: true,
    desc: "Tangy and aromatic rice cooked with tempered tomatoes, mustard seeds, and fresh curry leaves.",
  ),
  FoodItem(
    id: "item-3",
    canteenId: "canteen-1",
    name: "Standard Veg Meals",
    price: 90.0,
    prepTime: "8 min",
    rating: "4.7",
    img: "🍱",
    category: "Veg Specials",
    isVeg: true,
    desc: "Complete South Indian meals with Steamed Rice, Sambar, Rasam, Curd, and Special Poriyal.",
  ),
  FoodItem(
    id: "item-4",
    canteenId: "canteen-1",
    name: "Chapathi Kurma Combo",
    price: 40.0,
    prepTime: "5 min",
    rating: "4.5",
    img: "🫓",
    category: "Veg Specials",
    isVeg: true,
    desc: "2 pieces of soft whole-wheat chapathis served with aromatic vegetable kurma.",
  ),
  FoodItem(
    id: "item-5",
    canteenId: "canteen-1",
    name: "Special Chicken Biryani",
    price: 160.0,
    prepTime: "12 min",
    rating: "4.9",
    img: "🍚",
    category: "Non-Veg Specials",
    isVeg: false,
    desc: "Premium basmati rice layered with slow-cooked spiced chicken, served with onion raita.",
  ),
  FoodItem(
    id: "item-6",
    canteenId: "canteen-1",
    name: "Egg & Chicken Mixed Rice",
    price: 80.0,
    prepTime: "9 min",
    rating: "4.7",
    img: "🍳",
    category: "Non-Veg Specials",
    isVeg: false,
    desc: "Stir-fried basmati rice cooked with shredded chicken, scrambled egg, and scallions.",
  ),
  FoodItem(
    id: "item-7",
    canteenId: "canteen-1",
    name: "Malabar Parotta Combo",
    price: 100.0,
    prepTime: "8 min",
    rating: "4.8",
    img: "🫓",
    category: "Non-Veg Specials",
    isVeg: false,
    desc: "2 flaky layered Malabar parottas served with spicy chicken gravy.",
  ),
  FoodItem(
    id: "item-8",
    canteenId: "canteen-2",
    name: "Fresh Mango Juice",
    price: 50.0,
    prepTime: "3 min",
    rating: "4.7",
    img: "🥭",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Thick and chilled mango nectar squeezed from sweet ripe campus mangoes.",
  ),
  FoodItem(
    id: "item-9",
    canteenId: "canteen-2",
    name: "Fresh Watermelon Juice",
    price: 45.0,
    prepTime: "3 min",
    rating: "4.6",
    img: "🍉",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Refreshing, hydrating watermelon juice blended with a hint of mint and black salt.",
  ),
  FoodItem(
    id: "item-10",
    canteenId: "canteen-2",
    name: "Fresh Apple Juice",
    price: 60.0,
    prepTime: "4 min",
    rating: "4.5",
    img: "🍎",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Pure red apple juice extracted fresh, rich in vitamins with no added sugar.",
  ),
  FoodItem(
    id: "item-11",
    canteenId: "canteen-2",
    name: "Premium Dragon Fruit Juice",
    price: 70.0,
    prepTime: "4 min",
    rating: "4.8",
    img: "🥤",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Vibrant pink dragon fruit pulp blended with light honey and crushed ice.",
  ),
  FoodItem(
    id: "item-12",
    canteenId: "canteen-2",
    name: "Cold Coffee with Ice Cream",
    price: 60.0,
    prepTime: "4 min",
    rating: "4.8",
    img: "☕",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Double-shot espresso blended cold brew topped with a rich vanilla scoop.",
  ),
  FoodItem(
    id: "item-13",
    canteenId: "canteen-2",
    name: "Mineral Water Bottle (1L)",
    price: 20.0,
    prepTime: "1 min",
    rating: "4.9",
    img: "🍼",
    category: "Beverages & Juices",
    isVeg: true,
    desc: "Chilled, packaged mineral water bottle with electrolytes.",
  ),
  FoodItem(
    id: "item-14",
    canteenId: "canteen-3",
    name: "Hot Veg Samosa (2 Pcs)",
    price: 30.0,
    prepTime: "3 min",
    rating: "4.6",
    img: "🥟",
    category: "Snacks & Desserts",
    isVeg: true,
    desc: "Crispy fried pastry triangles stuffed with spiced potatoes and green peas, served with sweet chutney.",
  ),
  FoodItem(
    id: "item-15",
    canteenId: "canteen-3",
    name: "Cheese Grilled Sandwich",
    price: 65.0,
    prepTime: "5 min",
    rating: "4.6",
    img: "🥪",
    category: "Snacks & Desserts",
    isVeg: true,
    desc: "Golden toasted bread stuffed with molten mozzarella cheese, capsicum, and sweet corn.",
  ),
  FoodItem(
    id: "item-16",
    canteenId: "canteen-3",
    name: "Fudge Chocolate Brownie",
    price: 75.0,
    prepTime: "5 min",
    rating: "4.9",
    img: "🍰",
    category: "Snacks & Desserts",
    isVeg: true,
    desc: "Warm fudgy dark chocolate cake loaded with walnuts and hot chocolate drizzle.",
  ),
  FoodItem(
    id: "item-17",
    canteenId: "canteen-3",
    name: "Gulab Jamun (2 Pcs)",
    price: 35.0,
    prepTime: "2 min",
    rating: "4.7",
    img: "🍩",
    category: "Snacks & Desserts",
    isVeg: true,
    desc: "Classic soft fried cottage cheese balls soaked in warm sweet cardamom sugar syrup.",
  )
];
